// src/components/ModalForm/index.tsx
"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { Input } from "../Input";
import { Button } from "../Button";
import { ConsentCheckbox } from "../ConsentCheckbox";
import { Icon } from "@iconify/react";
import { isValidEmail } from "@/utils";
import { createUser } from "@/lib/api";
import { toast } from "react-toastify";
import clsx from "clsx";

interface ModalFormProps {
  isOpen: boolean;
  onClose: () => void;
}

interface FormState {
  name: string;
  email: string;
  password: string;
}

const formDefaultValue = {
  name: "",
  email: "",
  password: "",
};

export const ModalForm = ({ isOpen, onClose }: ModalFormProps) => {
  const [accepted, setAccepted] = useState(false);
  const [visible, setVisible] = useState(true);
  const [form, setForm] = useState<FormState>(formDefaultValue);
  const [errors, setErrors] = useState<FormState>(formDefaultValue);

  useEffect(() => {
    setAccepted(false);
    setErrors(formDefaultValue);
    setVisible(true);
  }, [isOpen]);

  useEffect(() => {
    if (isOpen) document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = "auto";
    };
  }, [isOpen]);

  const handleAccepted = () => {
    setAccepted(!accepted);
  };

  const handleInputValue = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { id, value } = e.target;
    if (!visible) return;
    setForm((prev) => ({
      ...prev,
      [id]: value,
    }));
  };

  const validateInputValue = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { id, value } = e.target;
    if (!visible) return;
    setErrors((prev) => ({
      ...prev,
      [id]: value ? "" : "Preencha este campo corretamente.",
    }));
  };

  const validateEmailValue = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { id, value } = e.target;
    if (!visible) return;
    setErrors((prev) => ({
      ...prev,
      [id]: isValidEmail(value) ? "" : "Preencha este campo corretamente.",
    }));
  };

  const isDisabled = () => !accepted || Object.values(errors).some((error) => error !== "");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const newErrors = {
      name: form.name ? "" : "Preencha este campo corretamente.",
      email: isValidEmail(form.email)
        ? ""
        : "Preencha este campo corretamente.",
      password: form.password ? "" : "Preencha este campo corretamente.",
    };

    setErrors(newErrors);

    const hasErrors = Object.values(newErrors).some(Boolean);
    if (hasErrors || !accepted) return;

    try {
      await createUser(form);
      toast.success("Conta criada com sucesso!");
      onClose();
      setForm(formDefaultValue);
      setAccepted(false);
    } catch (error: unknown) {
      if (error instanceof Error) {
        toast.error(error.message);
      } else {
        toast.error("Erro inesperado ao criar conta.");
      }
    }

  };

  const handleClose = () => {
    setVisible(false);
    setTimeout(() => {
      onClose();
    }, 800);
  };

  return (
    isOpen && (
      <div
        className="absolute top-0 left-0 w-full h-full bg-black/75 flex items-center justify-center z-50 px-8 md:px-12"
        role="dialog"
        aria-modal="true"
      >
        <form
          onSubmit={handleSubmit}
          className={clsx(
            "w-full max-w-3xl bg-offwhite h-full px-12 md:px-24 py-12 flex flex-col items-center shadow-lg relative gap-8",
            visible
              ? "animate-fade-up animate-once animate-duration-[750ms]"
              : "animate-fade animate-once animate-reverse animate-duration-[750ms]"
          )}
        >
          <button
            type="button"
            className="absolute p-1 rounded-full right-2 top-2 bg-gray-dark cursor-pointer"
            onClick={handleClose}
            aria-label="Fechar modal"
          >
            <Icon
              icon="material-symbols:close"
              className="text-white text-2xl"
            />
          </button>
          <Image
            width={355}
            height={261}
            src="/modal-register.png"
            alt="Pessoa ao lado de um smartphone exibindo uma interface com botão ativado, simbolizando a criação de conta."
          />

          <h2 className="text-xl font-bold">
            Preencha os campos abaixo para criar sua conta corrente!
          </h2>

          <Input
            id="name"
            value={form.name}
            error={visible ? errors.name : ""}
            onBlur={validateInputValue}
            onChange={handleInputValue}
            label="Nome"
            placeholder="Digite seu nome completo"
            variant="form"
          />
          <Input
            type="email"
            id="email"
            value={form.email}
            error={visible ? errors.email : ""}
            onChange={handleInputValue}
            onBlur={validateEmailValue}
            label="E-mail"
            placeholder="Digite seu email"
            variant="form"
          />
          <Input
            id="password"
            value={form.password}
            error={visible ? errors.password : ""}
            onChange={handleInputValue}
            onBlur={validateInputValue}
            type="password"
            label="Senha"
            placeholder="Digite sua senha"
            variant="form"
          />

          <ConsentCheckbox checked={accepted} onChange={handleAccepted} />

          <Button variant="red" type="submit" disabled={isDisabled()}>
            Criar conta
          </Button>
        </form>
      </div>
    )
  );
};

// apps/home/src/components/ModalForm.vue
<script setup lang="ts">
import { ref, reactive, computed, watch, nextTick } from 'vue';
import Button from './Button/Button.vue';
import { useAuth } from '../composables/useAuth';
import { redirectToDashboard } from '../config';
import { Icon } from "@iconify/vue";

interface Props {
  isOpen: boolean;
}

interface Emits {
  close: [];
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

// Auth composable
const { register, loading: authLoading, error: authError } = useAuth();

const accepted = ref(false);
const visible = ref(true);

const form = reactive({
  name: '',
  email: '',
  password: ''
});

const errors = reactive({
  name: '',
  email: '',
  password: ''
});

const formDefaultValue = {
  name: '',
  email: '',
  password: ''
};

const isValidEmail = (email: string): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

const isDisabled = computed(() => {
  return !accepted.value || Object.values(errors).some(error => error !== '') || authLoading.value;
});

watch(() => props.isOpen, (newValue) => {
  if (newValue) {
    accepted.value = false;
    Object.assign(errors, formDefaultValue);
    visible.value = true;
    document.body.style.overflow = 'hidden';
  } else {
    document.body.style.overflow = 'auto';
  }
});

const handleAccepted = () => {
  accepted.value = !accepted.value;
};

const handleInputValue = (field: keyof typeof form, value: string) => {
  if (!visible.value) return;
  form[field] = value;
};

const validateInputValue = (field: keyof typeof form, value: string) => {
  if (!visible.value) return;
  errors[field] = value ? '' : 'Preencha este campo corretamente.';
};

const validateEmailValue = (value: string) => {
  if (!visible.value) return;
  errors.email = isValidEmail(value) ? '' : 'Preencha este campo corretamente.';
};

const handleSubmit = async (e: Event) => {
  e.preventDefault();

  const newErrors = {
    name: form.name ? '' : 'Preencha este campo corretamente.',
    email: isValidEmail(form.email) ? '' : 'Preencha este campo corretamente.',
    password: form.password ? '' : 'Preencha este campo corretamente.'
  };

  Object.assign(errors, newErrors);

  const hasErrors = Object.values(newErrors).some(Boolean);
  if (hasErrors || !accepted.value) return;

  try {
    await register({
      name: form.name,
      email: form.email,
      password: form.password
    });
    
    alert('Conta criada com sucesso! Redirecionando para o dashboard...');
    handleClose();
    Object.assign(form, formDefaultValue);
    accepted.value = false;
    
    // Debug: verificar se sessão foi salva
    console.log('Sessão salva no localStorage:', localStorage.getItem('bank-app-session'));
    
    // Redirecionar para o dashboard Next.js com delay maior
    setTimeout(() => {
      console.log('Redirecionando para dashboard...');
      redirectToDashboard();
    }, 2000);
  } catch (error) {
    console.error('Erro ao criar conta:', error);
    // O erro já é tratado pelo composable, mas podemos mostrar feedback adicional
    if (authError.value) {
      alert(authError.value);
    }
  }
};

const handleClose = () => {
  visible.value = false;
  setTimeout(() => {
    emit('close');
  }, 800);
};
</script>

<template>
  <div
    v-if="isOpen"
    class="absolute top-0 left-0 w-full h-full bg-black/75 flex items-center justify-center z-50 px-8 md:px-12"
    role="dialog"
    aria-modal="true"
  >
    <form
      @submit="handleSubmit"
      :class="[
        'w-full max-w-3xl bg-offwhite h-full px-12 md:px-24 py-12 flex flex-col items-center shadow-lg relative gap-8',
        visible 
          ? 'animate-fade-up animate-once animate-duration-[750ms]'
          : 'animate-fade animate-once animate-reverse animate-duration-[750ms]'
      ]"
    >
      <button
        type="button"
        class="absolute p-1 rounded-full right-2 top-2 bg-gray-dark cursor-pointer"
        @click="handleClose"
        aria-label="Fechar modal"
      >
        <Icon icon="material-symbols:close" class="text-white text-2xl" />
      </button>

      <img
        width="355"
        height="261"
        src="/modal-register.png"
        alt="Pessoa ao lado de um smartphone exibindo uma interface com botão ativado, simbolizando a criação de conta."
        class="w-[355px] h-[261px]"
      />

      <h2 class="text-xl font-bold">
        Preencha os campos abaixo para criar sua conta corrente!
      </h2>
      <div class="w-full">
        <label for="name" class="block text-sm font-medium text-gray-700 mb-1">Nome</label>
        <input
          id="name"
          type="text"
          :value="form.name"
          @input="handleInputValue('name', ($event.target as HTMLInputElement).value)"
          @blur="validateInputValue('name', ($event.target as HTMLInputElement).value)"
          placeholder="Digite seu nome completo"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green focus:border-transparent"
        />
        <p v-if="visible && errors.name" class="text-red-500 text-sm mt-1">{{ errors.name }}</p>
      </div>

      <div class="w-full">
        <label for="email" class="block text-sm font-medium text-gray-700 mb-1">E-mail</label>
        <input
          id="email"
          type="email"
          :value="form.email"
          @input="handleInputValue('email', ($event.target as HTMLInputElement).value)"
          @blur="validateEmailValue(($event.target as HTMLInputElement).value)"
          placeholder="Digite seu email"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green focus:border-transparent"
        />
        <p v-if="visible && errors.email" class="text-red-500 text-sm mt-1">{{ errors.email }}</p>
      </div>

      <div class="w-full">
        <label for="password" class="block text-sm font-medium text-gray-700 mb-1">Senha</label>
        <input
          id="password"
          type="password"
          :value="form.password"
          @input="handleInputValue('password', ($event.target as HTMLInputElement).value)"
          @blur="validateInputValue('password', ($event.target as HTMLInputElement).value)"
          placeholder="Digite sua senha"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green focus:border-transparent"
        />
        <p v-if="visible && errors.password" class="text-red-500 text-sm mt-1">{{ errors.password }}</p>
      </div>

      <label
        for="consent-checkbox"
        class="flex items-center gap-2 cursor-pointer select-none"
      >
        <input
          id="consent-checkbox"
          type="checkbox"
          :checked="accepted"
          @change="handleAccepted"
          class="hidden"
        />

        <div
          :class="[
            'w-5 h-5 transition-all cursor-pointer border-2 border-green rounded-md flex items-center justify-center',
            accepted ? 'bg-green' : 'bg-white'
          ]"
        >
          <Icon v-if="accepted" icon="material-symbols:close" class="text-white text-2xl" />
        </div>
        <p class="flex-1 text-sm text-black">
          Li e estou ciente quanto às condições de tratamento dos meus dados
          conforme descrito na
          <span class="underline">Política de Privacidade do banco</span>.
        </p>
      </label>

      <Button 
        variant="red" 
        type="submit" 
        :disabled="isDisabled"
      >
        {{ authLoading ? 'Criando conta...' : 'Criar conta' }}
      </Button>
    </form>
  </div>
</template>

<style scoped>
/* Estilos específicos do modal se necessário */
</style>
